name: My Jekyll Skeleton
markdown: redcarpet
pygments: true

# Modify these values
# url: http://localhost:4000
url: http://kiransamudrala.github.io/
baseurl: /git-out-there-little-star
imgbase: /assets

# User information
user: "Kiran"

email: someone@me.com
