name: My Jekyll Skeleton
markdown: redcarpet
pygments: true

# Modify these values
url: http://tonyfast.com/
baseurl: /git-out-there-little-star
imgbase: /assets

# User information
user: "Tony Fast"
