name: My Jekyll Skeleton
markdown: redcarpet
pygments: true

# Modify these values
# url: http://localhost:4000
url: http://tonyfast.com
baseurl: /git-out-there-little-star
imgbase: /assets

# User information
user: "Tony Fast"
